//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Settings/ControlMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlMap : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlMap"",
    ""maps"": [
        {
            ""name"": ""Move"",
            ""id"": ""908f86c8-813f-46e2-a648-0d5ede0198f9"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""5343d182-846d-4faf-8018-e6f83475cfa3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MousePos"",
                    ""type"": ""Value"",
                    ""id"": ""18d532a4-e182-4127-a47a-473e8d5ec72c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StartBuild"",
                    ""type"": ""Button"",
                    ""id"": ""1a8cb26c-d87d-4f8d-aae7-bbd839a93d0d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CheckUnitDetail"",
                    ""type"": ""Button"",
                    ""id"": ""990bc3da-2d5b-4fd5-8382-0d3d08134a5b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""de7f572a-2fb8-4677-9abc-86ebbeeeddd6"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""6b93e1b1-e977-4b3c-b7e5-b87782557747"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ec51498b-187b-4581-a243-2afb34c688f2"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""daf97a92-8968-4710-ad17-178d730aec3b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d93acd0c-b70f-4bd6-8800-544bf0859ea4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""089517da-a4ce-496c-a0ea-e36ec9e345e5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ecb0fadf-7248-4d1d-ac8f-e87ccf0fc01a"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartBuild"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae9744fc-ad40-4042-87b7-254b0467be6a"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CheckUnitDetail"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""d05e7cd2-487a-460e-86eb-1a06a3afb474"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""39fc4173-428b-418b-8dca-9589285afdb9"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9f2201c6-fd3a-4c5a-a310-d32140a37a4c"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3d75ddbc-aef1-4994-814e-3456865c8932"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Build"",
            ""id"": ""ced9ee2f-21e7-46b9-bdaf-247f5ce477ea"",
            ""actions"": [
                {
                    ""name"": ""BuildUnit"",
                    ""type"": ""Button"",
                    ""id"": ""ae96a074-bf27-4f3c-872b-1ff872d02927"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CheckUnitDetail"",
                    ""type"": ""Button"",
                    ""id"": ""fae833f3-27ab-429d-a296-2cfc99bf6cd8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftBuild"",
                    ""type"": ""Button"",
                    ""id"": ""b82c5972-988a-45fa-979d-8b3efa2e493d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateDir"",
                    ""type"": ""Button"",
                    ""id"": ""db70cac9-493e-49ec-938d-fa4da35974be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeBuildUnit"",
                    ""type"": ""Button"",
                    ""id"": ""e7ad24c5-bb31-4953-a352-139d80d58996"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""1546ea7a-1331-4d6c-8881-0496a5199551"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""0a98653d-4704-40bc-88c6-2643ff2b4b0a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""5e336461-82dd-4706-8969-d3948bf5e593"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePos"",
                    ""type"": ""Value"",
                    ""id"": ""c86bccbf-477d-4ee3-b19f-9bf5a62f1b15"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""095dd8d7-0c76-494d-b3b3-42252481fa07"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BuildUnit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89c30d51-f128-4717-a1e3-cb5109c50f83"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftBuild"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76f699eb-40a1-4695-b2d4-412fece24b83"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateDir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b047991-2f59-4107-80f8-6134c44d70fe"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeBuildUnit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""7c2cc4c7-22e0-49ca-b5de-1e78f9818f3b"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""6bece98c-083a-466c-9152-1ca36ab4b345"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""1f438c37-305a-49fe-a57c-00f190b4fad6"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""b677e1ac-e5a0-4639-a220-09c61c2a2ce8"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1919ddae-2fe8-48f1-8a2c-09c5b967ecc9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""73f3e2d6-58bc-4100-b61f-4525689c72c3"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c710610c-5128-450c-9b73-62ee93429696"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1a33bfd5-7315-446e-887b-51bed0632712"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4bd92c26-9ee6-448f-bf89-e36a248e0522"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fce9dc6e-ea1e-400c-a194-85209682dee4"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CheckUnitDetail"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8def552f-6a72-4d5b-a774-9016f705b33d"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""8dac56f1-c5bc-47e4-b86c-8d17ee07f49c"",
            ""actions"": [],
            ""bindings"": []
        }
    ],
    ""controlSchemes"": []
}");
        // Move
        m_Move = asset.FindActionMap("Move", throwIfNotFound: true);
        m_Move_Move = m_Move.FindAction("Move", throwIfNotFound: true);
        m_Move_MousePos = m_Move.FindAction("MousePos", throwIfNotFound: true);
        m_Move_StartBuild = m_Move.FindAction("StartBuild", throwIfNotFound: true);
        m_Move_CheckUnitDetail = m_Move.FindAction("CheckUnitDetail", throwIfNotFound: true);
        m_Move_Zoom = m_Move.FindAction("Zoom", throwIfNotFound: true);
        // Build
        m_Build = asset.FindActionMap("Build", throwIfNotFound: true);
        m_Build_BuildUnit = m_Build.FindAction("BuildUnit", throwIfNotFound: true);
        m_Build_CheckUnitDetail = m_Build.FindAction("CheckUnitDetail", throwIfNotFound: true);
        m_Build_LeftBuild = m_Build.FindAction("LeftBuild", throwIfNotFound: true);
        m_Build_RotateDir = m_Build.FindAction("RotateDir", throwIfNotFound: true);
        m_Build_ChangeBuildUnit = m_Build.FindAction("ChangeBuildUnit", throwIfNotFound: true);
        m_Build_Zoom = m_Build.FindAction("Zoom", throwIfNotFound: true);
        m_Build_Move = m_Build.FindAction("Move", throwIfNotFound: true);
        m_Build_Cancel = m_Build.FindAction("Cancel", throwIfNotFound: true);
        m_Build_MousePos = m_Build.FindAction("MousePos", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Move
    private readonly InputActionMap m_Move;
    private IMoveActions m_MoveActionsCallbackInterface;
    private readonly InputAction m_Move_Move;
    private readonly InputAction m_Move_MousePos;
    private readonly InputAction m_Move_StartBuild;
    private readonly InputAction m_Move_CheckUnitDetail;
    private readonly InputAction m_Move_Zoom;
    public struct MoveActions
    {
        private @ControlMap m_Wrapper;
        public MoveActions(@ControlMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Move_Move;
        public InputAction @MousePos => m_Wrapper.m_Move_MousePos;
        public InputAction @StartBuild => m_Wrapper.m_Move_StartBuild;
        public InputAction @CheckUnitDetail => m_Wrapper.m_Move_CheckUnitDetail;
        public InputAction @Zoom => m_Wrapper.m_Move_Zoom;
        public InputActionMap Get() { return m_Wrapper.m_Move; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MoveActions set) { return set.Get(); }
        public void SetCallbacks(IMoveActions instance)
        {
            if (m_Wrapper.m_MoveActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnMove;
                @MousePos.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnMousePos;
                @MousePos.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnMousePos;
                @MousePos.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnMousePos;
                @StartBuild.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnStartBuild;
                @StartBuild.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnStartBuild;
                @StartBuild.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnStartBuild;
                @CheckUnitDetail.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnCheckUnitDetail;
                @CheckUnitDetail.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnCheckUnitDetail;
                @CheckUnitDetail.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnCheckUnitDetail;
                @Zoom.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnZoom;
            }
            m_Wrapper.m_MoveActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @MousePos.started += instance.OnMousePos;
                @MousePos.performed += instance.OnMousePos;
                @MousePos.canceled += instance.OnMousePos;
                @StartBuild.started += instance.OnStartBuild;
                @StartBuild.performed += instance.OnStartBuild;
                @StartBuild.canceled += instance.OnStartBuild;
                @CheckUnitDetail.started += instance.OnCheckUnitDetail;
                @CheckUnitDetail.performed += instance.OnCheckUnitDetail;
                @CheckUnitDetail.canceled += instance.OnCheckUnitDetail;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
            }
        }
    }
    public MoveActions @Move => new MoveActions(this);

    // Build
    private readonly InputActionMap m_Build;
    private IBuildActions m_BuildActionsCallbackInterface;
    private readonly InputAction m_Build_BuildUnit;
    private readonly InputAction m_Build_CheckUnitDetail;
    private readonly InputAction m_Build_LeftBuild;
    private readonly InputAction m_Build_RotateDir;
    private readonly InputAction m_Build_ChangeBuildUnit;
    private readonly InputAction m_Build_Zoom;
    private readonly InputAction m_Build_Move;
    private readonly InputAction m_Build_Cancel;
    private readonly InputAction m_Build_MousePos;
    public struct BuildActions
    {
        private @ControlMap m_Wrapper;
        public BuildActions(@ControlMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @BuildUnit => m_Wrapper.m_Build_BuildUnit;
        public InputAction @CheckUnitDetail => m_Wrapper.m_Build_CheckUnitDetail;
        public InputAction @LeftBuild => m_Wrapper.m_Build_LeftBuild;
        public InputAction @RotateDir => m_Wrapper.m_Build_RotateDir;
        public InputAction @ChangeBuildUnit => m_Wrapper.m_Build_ChangeBuildUnit;
        public InputAction @Zoom => m_Wrapper.m_Build_Zoom;
        public InputAction @Move => m_Wrapper.m_Build_Move;
        public InputAction @Cancel => m_Wrapper.m_Build_Cancel;
        public InputAction @MousePos => m_Wrapper.m_Build_MousePos;
        public InputActionMap Get() { return m_Wrapper.m_Build; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BuildActions set) { return set.Get(); }
        public void SetCallbacks(IBuildActions instance)
        {
            if (m_Wrapper.m_BuildActionsCallbackInterface != null)
            {
                @BuildUnit.started -= m_Wrapper.m_BuildActionsCallbackInterface.OnBuildUnit;
                @BuildUnit.performed -= m_Wrapper.m_BuildActionsCallbackInterface.OnBuildUnit;
                @BuildUnit.canceled -= m_Wrapper.m_BuildActionsCallbackInterface.OnBuildUnit;
                @CheckUnitDetail.started -= m_Wrapper.m_BuildActionsCallbackInterface.OnCheckUnitDetail;
                @CheckUnitDetail.performed -= m_Wrapper.m_BuildActionsCallbackInterface.OnCheckUnitDetail;
                @CheckUnitDetail.canceled -= m_Wrapper.m_BuildActionsCallbackInterface.OnCheckUnitDetail;
                @LeftBuild.started -= m_Wrapper.m_BuildActionsCallbackInterface.OnLeftBuild;
                @LeftBuild.performed -= m_Wrapper.m_BuildActionsCallbackInterface.OnLeftBuild;
                @LeftBuild.canceled -= m_Wrapper.m_BuildActionsCallbackInterface.OnLeftBuild;
                @RotateDir.started -= m_Wrapper.m_BuildActionsCallbackInterface.OnRotateDir;
                @RotateDir.performed -= m_Wrapper.m_BuildActionsCallbackInterface.OnRotateDir;
                @RotateDir.canceled -= m_Wrapper.m_BuildActionsCallbackInterface.OnRotateDir;
                @ChangeBuildUnit.started -= m_Wrapper.m_BuildActionsCallbackInterface.OnChangeBuildUnit;
                @ChangeBuildUnit.performed -= m_Wrapper.m_BuildActionsCallbackInterface.OnChangeBuildUnit;
                @ChangeBuildUnit.canceled -= m_Wrapper.m_BuildActionsCallbackInterface.OnChangeBuildUnit;
                @Zoom.started -= m_Wrapper.m_BuildActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_BuildActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_BuildActionsCallbackInterface.OnZoom;
                @Move.started -= m_Wrapper.m_BuildActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_BuildActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_BuildActionsCallbackInterface.OnMove;
                @Cancel.started -= m_Wrapper.m_BuildActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_BuildActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_BuildActionsCallbackInterface.OnCancel;
                @MousePos.started -= m_Wrapper.m_BuildActionsCallbackInterface.OnMousePos;
                @MousePos.performed -= m_Wrapper.m_BuildActionsCallbackInterface.OnMousePos;
                @MousePos.canceled -= m_Wrapper.m_BuildActionsCallbackInterface.OnMousePos;
            }
            m_Wrapper.m_BuildActionsCallbackInterface = instance;
            if (instance != null)
            {
                @BuildUnit.started += instance.OnBuildUnit;
                @BuildUnit.performed += instance.OnBuildUnit;
                @BuildUnit.canceled += instance.OnBuildUnit;
                @CheckUnitDetail.started += instance.OnCheckUnitDetail;
                @CheckUnitDetail.performed += instance.OnCheckUnitDetail;
                @CheckUnitDetail.canceled += instance.OnCheckUnitDetail;
                @LeftBuild.started += instance.OnLeftBuild;
                @LeftBuild.performed += instance.OnLeftBuild;
                @LeftBuild.canceled += instance.OnLeftBuild;
                @RotateDir.started += instance.OnRotateDir;
                @RotateDir.performed += instance.OnRotateDir;
                @RotateDir.canceled += instance.OnRotateDir;
                @ChangeBuildUnit.started += instance.OnChangeBuildUnit;
                @ChangeBuildUnit.performed += instance.OnChangeBuildUnit;
                @ChangeBuildUnit.canceled += instance.OnChangeBuildUnit;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @MousePos.started += instance.OnMousePos;
                @MousePos.performed += instance.OnMousePos;
                @MousePos.canceled += instance.OnMousePos;
            }
        }
    }
    public BuildActions @Build => new BuildActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    public struct UIActions
    {
        private @ControlMap m_Wrapper;
        public UIActions(@ControlMap wrapper) { m_Wrapper = wrapper; }
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
            }
        }
    }
    public UIActions @UI => new UIActions(this);
    public interface IMoveActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnMousePos(InputAction.CallbackContext context);
        void OnStartBuild(InputAction.CallbackContext context);
        void OnCheckUnitDetail(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
    }
    public interface IBuildActions
    {
        void OnBuildUnit(InputAction.CallbackContext context);
        void OnCheckUnitDetail(InputAction.CallbackContext context);
        void OnLeftBuild(InputAction.CallbackContext context);
        void OnRotateDir(InputAction.CallbackContext context);
        void OnChangeBuildUnit(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnMousePos(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
    }
}
